### ISSUE TITLE
registry docs are out of date

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-grid#84] opened 2015-05-20 11:01 UTC
Lack any mention of `oGridColumn()`. Think this needs a new minor release
@AlbertoElias

**Comment by AlbertoElias** [comment] 2015-05-20 11:09
This is a duplicate of #81 and it was addressed in #83

**Comment by AlbertoElias** [comment] 2015-05-20 11:10
Ah right, got it, patch release made! Thanks!

**Closed by AlbertoElias** 2015-05-20 11:10 UTC
